import os
import json
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"


# ---------------------------------------------------------------------------
# Audit log helpers
# ---------------------------------------------------------------------------

def load_log() -> list:
    """Load all entries from the JSON audit log. Returns empty list if missing."""
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            return []


def save_log(entries: list) -> None:
    """Persist the full list of entries back to disk."""
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)


def append_log_entry(entry: dict) -> None:
    """Append a single structured entry to the audit log."""
    entries = load_log()
    entries.append(entry)
    save_log(entries)


# ---------------------------------------------------------------------------
# Signal 1 — Groq LLM classification
# ---------------------------------------------------------------------------

LLM_PROMPT = """You are an AI content detection assistant. Your job is to assess whether a piece of text was written by a human or generated by an AI writing tool.

Analyze the text below and return ONLY a valid JSON object with a single field: "llm_score".

The score must be a float between 0.0 and 1.0:
- 1.0 means you are highly confident the text is AI-generated
- 0.0 means you are highly confident the text is human-written
- Use values between 0.3 and 0.7 for genuinely ambiguous cases

Signals of AI-generated text include: overly structured arguments, hedged phrasing (e.g. "it is important to note"), uniform sentence rhythm, generic vocabulary, and lack of personal voice.

Signals of human-written text include: irregular sentence lengths, personal anecdotes, colloquialisms, typos, strong or idiosyncratic opinions, and emotional register.

Respond with ONLY the JSON object. No explanation, no markdown, no extra text.

Example response: {{"llm_score": 0.82}}

Text to analyze:
\"\"\"
{text}
\"\"\""""


def get_llm_score(text: str) -> float:
    """
    Call Groq to get a semantic AI-likelihood score.

    Returns a float in [0.0, 1.0] where 1.0 = likely AI-generated.
    Falls back to 0.5 (uncertain) on any error.
    """
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "user",
                    "content": LLM_PROMPT.format(text=text),
                }
            ],
            temperature=0.0,   # deterministic output
            max_tokens=50,
        )

        raw = response.choices[0].message.content.strip()

        # Strip markdown fences if the model adds them despite instructions
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        parsed = json.loads(raw)
        score = float(parsed["llm_score"])
        return max(0.0, min(1.0, score))   # clamp to [0, 1]

    except Exception as e:
        app.logger.error(f"get_llm_score error: {e}")
        return 0.5   # fallback: uncertain


# ---------------------------------------------------------------------------
# Signal 2 — Stylometric heuristics
# ---------------------------------------------------------------------------

import re
import math


def get_stylometric_score(text: str) -> float:
    """
    Compute a structural AI-likelihood score from two stylometric metrics:
      1. Sentence length variance  — AI text is more uniform (low variance)
      2. Type-token ratio (TTR)    — AI text has moderate lexical diversity

    Both metrics are normalized so that more AI-like → closer to 1.0.
    Returns a float in [0.0, 1.0].
    """
    # --- Tokenize into sentences and words ---
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    words = re.findall(r'\b\w+\b', text.lower())

    # Need at least 2 sentences and 10 words for meaningful signal
    if len(sentences) < 2 or len(words) < 10:
        return 0.5  # too short to assess — return uncertain

    # --- Metric 1: Sentence length variance ---
    sent_lengths = [len(re.findall(r'\b\w+\b', s)) for s in sentences]
    mean_len = sum(sent_lengths) / len(sent_lengths)
    variance = sum((l - mean_len) ** 2 for l in sent_lengths) / len(sent_lengths)

    # High variance = human-like. Normalize: clamp variance to [0, 100],
    # then invert so low variance → score near 1.0 (AI-like).
    variance_clamped = min(variance, 100.0)
    variance_score = 1.0 - (variance_clamped / 100.0)

    # --- Metric 2: Type-token ratio (TTR) ---
    unique_words = len(set(words))
    ttr = unique_words / len(words)

    # Human writing tends toward higher TTR (more diverse vocabulary).
    # AI writing clusters around moderate TTR (~0.50–0.70 at typical lengths).
    # Normalize: TTR below 0.6 → more AI-like → score near 1.0.
    # TTR above 0.6 → more human-like → score near 0.0.
    ttr_score = max(0.0, min(1.0, (0.6 - ttr) / 0.6 + 0.5))
    ttr_score = max(0.0, min(1.0, ttr_score))

    # --- Combine into single stylometric score ---
    stylometric_score = (variance_score + ttr_score) / 2.0
    return round(max(0.0, min(1.0, stylometric_score)), 4)


# ---------------------------------------------------------------------------
# Confidence scoring
# ---------------------------------------------------------------------------

def compute_confidence(llm_score: float, stylometric_score: float) -> tuple:
    """
    Combine both signal scores into a single calibrated confidence value.

    Weights (from planning.md):
        LLM signal:          0.6  (semantic — stronger signal)
        Stylometric signal:  0.4  (structural — corroborating signal)

    Thresholds:
        >= 0.65  → likely_ai
        >  0.35  → uncertain
        <= 0.35  → likely_human

    Returns: (confidence: float, attribution: str)
    """
    confidence = round((0.6 * llm_score) + (0.4 * stylometric_score), 4)

    if confidence >= 0.65:
        attribution = "likely_ai"
    elif confidence > 0.35:
        attribution = "uncertain"
    else:
        attribution = "likely_human"

    return confidence, attribution


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    """
    Accept a text submission for attribution analysis.

    Request body (JSON):
        text        (str, required) — the content to classify
        creator_id  (str, required) — identifier for the submitting creator

    Returns (JSON):
        content_id         — unique ID for this submission (use for appeals)
        attribution        — "likely_ai" | "uncertain" | "likely_human"
        confidence         — float [0, 1] weighted combination of both signals
        label              — transparency label text shown to users
        llm_score          — raw Signal 1 output
        stylometric_score  — raw Signal 2 output
    """
    data = request.get_json(silent=True)

    # --- Input validation ---
    if not data:
        return jsonify({"error": "Request body must be JSON."}), 400
    if not data.get("text", "").strip():
        return jsonify({"error": "Field 'text' is required and cannot be empty."}), 400
    if not data.get("creator_id", "").strip():
        return jsonify({"error": "Field 'creator_id' is required."}), 400

    text = data["text"].strip()
    creator_id = data["creator_id"].strip()

    # --- Generate a unique content ID ---
    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    # --- Signal 1: Groq LLM ---
    llm_score = get_llm_score(text)

    # --- Signal 2: Stylometric heuristics ---
    stylometric_score = get_stylometric_score(text)

    # --- Confidence scoring: weighted combination ---
    confidence, attribution = compute_confidence(llm_score, stylometric_score)

    # --- Label (placeholder until Milestone 5) ---
    label = "[Label generation coming in Milestone 5]"

    # --- Write structured audit log entry ---
    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
        "status": "classified",
        "appeal_reasoning": None,
        "appeal_timestamp": None,
    }
    append_log_entry(log_entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
    }), 200


@app.route("/log", methods=["GET"])
def get_log():
    """
    Return all audit log entries as JSON, most recent first.
    In production this endpoint would require authentication.
    """
    entries = load_log()
    entries_desc = list(reversed(entries))
    return jsonify({"count": len(entries_desc), "entries": entries_desc}), 200


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    app.run(debug=True)